In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

**Load Data**

In [2]:
df = pd.read_csv('../Data/raw/world_bank_data_2025.csv')
df.head()

,country_name,country_id,year,Inflation (CPI %),GDP (Current USD),GDP per Capita (Current USD),Unemployment Rate (%),"Interest Rate (Real, %)","Inflation (GDP Deflator, %)",GDP Growth (% Annual),Current Account Balance (% GDP),Government Expense (% of GDP),Government Revenue (% of GDP),Tax Revenue (% of GDP),Gross National Income (USD),Public Debt (% of GDP)
0,Aruba,aw,2010,2.078141,2.453597e+09,24093.140151,NaN,11.666131,-1.223407,-2.733457,-18.752537,NaN,NaN,NaN,2.313385e+09,NaN
1,Aruba,aw,2011,4.316297,2.637859e+09,25712.384302,NaN,4.801974,4.005674,3.369237,-9.877656,NaN,NaN,NaN,2.391841e+09,NaN
2,Aruba,aw,2012,0.627472,2.615208e+09,25119.665545,NaN,8.200875,0.184033,-1.040800,3.473451,NaN,NaN,NaN,2.499118e+09,NaN
3,Aruba,aw,2013,-2.372065,2.727850e+09,25813.576727,NaN,10.709709,-1.995948,6.431483,-11.813206,NaN,NaN,NaN,2.563517e+09,NaN
4,Aruba,aw,2014,0.421441,2.790850e+09,26129.839062,NaN,3.213869,3.958897,-1.586575,-4.658577,NaN,NaN,NaN,2.688102e+09,NaN

**Understanding the data**

In [5]:
df.info()
df.describe()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3472 entries, 0 to 3471
Data columns (total 16 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   country_name                     3472 non-null   object
 1   country_id                       3472 non-null   object
 2   year                             3472 non-null   int64
 3   Inflation (CPI %)                2694 non-null   float64
 4   GDP (Current USD)                2933 non-null   float64
 5   GDP per Capita (Current USD)     2938 non-null   float64
 6   Unemployment Rate (%)            2795 non-null   float64
 7   Interest Rate (Real, %)          1735 non-null   float64
 8   Inflation (GDP Deflator, %)      2904 non-null   float64
 9   GDP Growth (% Annual)            2912 non-null   float64
 10  Current Account Balance (% GDP)  2563 non-null   float64
 11  Government Expense (% of GDP)    1820 non-null   float64
 12  Government Revenue (% of GDP)    1829 non-null   float64
 13  Tax Revenue (% of GDP)           1833 non-null   float64
 14  Gross National Income (USD)      2796 non-null   float64
 15  Public Debt (% of GDP)           852 non-null    float64
dtypes: float64(13), int64(1), object(2)
memory usage: 434.1+ KB

country_name                          0
country_id                            0
year                                  0
Inflation (CPI %)                   778
GDP (Current USD)                   539
GDP per Capita (Current USD)        534
Unemployment Rate (%)               677
Interest Rate (Real, %)            1737
Inflation (GDP Deflator, %)         568
GDP Growth (% Annual)               560
Current Account Balance (% GDP)     909
Government Expense (% of GDP)      1652
Government Revenue (% of GDP)      1643
Tax Revenue (% of GDP)             1639
Gross National Income (USD)         676
Public Debt (% of GDP)             2620
dtype: int64

**Select Columns**

In [7]:
df = df[['country_name',
            'year',
            'Inflation (CPI %)',
            'GDP Growth (% Annual)',
            'Interest Rate (Real, %)',
            'Unemployment Rate (%)',
            'Current Account Balance (% GDP)',
            'Public Debt (% of GDP)'
        ]]

In [9]:
df.columns = ['country',
    'year',
    'inflation',
    'gdp_growth',
    'interest_rate',
    'unemployment',
    'current_account',
    'debt']

In [10]:
df

,country,year,inflation,gdp_growth,interest_rate,unemployment,current_account,debt
0,Aruba,2010,2.078141,-2.733457,11.666131,NaN,-18.752537,NaN
1,Aruba,2011,4.316297,3.369237,4.801974,NaN,-9.877656,NaN
2,Aruba,2012,0.627472,-1.040800,8.200875,NaN,3.473451,NaN
3,Aruba,2013,-2.372065,6.431483,10.709709,NaN,-11.813206,NaN
4,Aruba,2014,0.421441,-1.586575,3.213869,NaN,-4.658577,NaN
...,...,...,...,...,...,...,...,...
3467,Zimbabwe,2021,98.546105,8.468017,-31.795551,9.540,1.278300,NaN
3468,Zimbabwe,2022,104.705171,6.139263,-36.833393,10.087,0.930064,NaN
3469,Zimbabwe,2023,NaN,5.336730,-73.540441,8.759,0.379995,NaN
3470,Zimbabwe,2024,NaN,NaN,NaN,8.554,NaN,NaN
3471,Zimbabwe,2025,NaN,NaN,NaN,NaN,NaN,NaN